from django.contrib import admin
from home.models import SliderContent,AfterSliderContent,PopularProducts,LatestProducts_Content,About_Content_Heading,About_Three_Content,About_Content_Paragraph,About_Content_Top_Down,VideoSection,Location,ContactUs,Logo

# Register your models here.

admin.site.register((SliderContent,AfterSliderContent,PopularProducts,LatestProducts_Content,About_Content_Heading,About_Three_Content,About_Content_Paragraph,About_Content_Top_Down,VideoSection,Location,ContactUs,Logo))
 
