# Generated by Django 2.2.6 on 2020-10-19 08:51

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AfterSliderContent',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('content', ckeditor.fields.RichTextField()),
            ],
        ),
        migrations.CreateModel(
            name='PopularProducts',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('price', models.CharField(max_length=200)),
                ('size', models.CharField(max_length=200)),
                ('material', models.CharField(max_length=200)),
                ('color', models.CharField(max_length=200)),
                ('imglink', models.CharField(blank=True, max_length=255)),
                ('content', ckeditor.fields.RichTextField()),
            ],
        ),
        migrations.RenameField(
            model_name='slidercontent',
            old_name='Content',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='slidercontent',
            old_name='Heading',
            new_name='heading',
        ),
    ]
